spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_socalial_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
     hibernate:
       ddl-auto: update
#           to display sql query in console
     show-sql: false
     properties:
       hibernate:
         format-sql: true
     database: postgresql
     database-platform: org.hibernate.dialect.PostgreSLDialect

#mail configuration
  mail:
    host: localhost
    port:1025
    username: akshay
    password: akshay
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000